DROP TABLE SALFORDMOVE.dbo.SENSOR_VOLTAGE;
DROP TABLE SALFORDMOVE.dbo.PENDING_CHANGES;
DROP TABLE SALFORDMOVE.dbo.BATTERY_STATUS;
DROP TABLE SALFORDMOVE.dbo.SIGNAL_STATUS;
DROP TABLE SALFORDMOVE.dbo.READINGS;
DROP TABLE SALFORDMOVE.dbo.DATA_TYPES;
DROP TABLE SALFORDMOVE.dbo.PLOT_LABELS;
DROP TABLE SALFORDMOVE.dbo.SENSORS;
DROP TABLE SALFORDMOVE.dbo.NETWORKS;
DROP TABLE SALFORDMOVE.dbo.APPLICATIONS;
GO